#!/usr/bin/env python3
"""
hv-convert.py — move Aether frontend colors onto the HV GUI Guidelines (v3.435) tokens.

Run from frontend/:   python3 scripts/hv-convert.py src            (dry run, prints a summary)
                      python3 scripts/hv-convert.py src --apply    (rewrite files)

What it does, per .ts/.tsx file (safe to re-run; already-converted code is left alone):
  1. Every color literal (#hex, rgba(), Tailwind arbitrary value) -> HV semantic token
       bg-[#241E19]/40  -> bg-hv-widget/40        '#F0A73C' -> 'rgb(var(--hv-brand))'
     Legacy Aether colors are first mapped to their HV Dark equivalent (LEGACY table),
     then snapped to the nearest token in the same HV family. Status colors used as
     text become *-fg so they stay readable in Light mode.
  2. text-white -> text-hv-text, except on solid accent buttons (white stays white).
  3. Translucent black wells (bg-black/NN, rgba(0,0,0,a) backgrounds) -> surface token;
     modal backdrops (fixed inset-0) keep HV Dim black.
  4. String-built alpha colors (color + '30', ${c}26) -> color-mix(), so tokens work.
  5. Known categorical maps get one HV Data color per category.
Tokens live in src/theme/hv-tokens.css (generated by scripts/hv-tokens.py).
"""
import colorsys, json, pathlib, re, sys
import importlib.util
_spec = importlib.util.spec_from_file_location('hvt', pathlib.Path(__file__).with_name('hv-tokens.py'))
_hvt = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(_hvt)
TOKENS = _hvt.TOKENS

# ── 1a. Legacy Aether palette -> HV Dark value ───────────────────────────────
LEGACY = {
    '00B8D4': '3B6BE6', '00D9FF': '487BFF', '020617': '101011', '06B6D4': '3B6BE6', '0B1222': '101011', '0E7490': '24459C',
    '0F1219': '101011', '0F172A': '181819', '0F3460': '182231', '100C08': '101011', '10B981': '00B960', '111827': '181819',
    '15110B': '101011', '16213E': '202021', '173B38': '182231', '191410': '181819', '1A1316': '181819', '1A1A2E': '181819',
    '1A1F2E': '202021', '1B1613': '181819', '1C1416': '181819', '1D2A4A': '1E2638', '1D4ED8': '3B6BE6', '1E293B': '202021',
    '1E3A24': '0F2E1F', '1E3A8A': '24459C', '1E7488': '24459C', '1F1719': '181819', '1F1A1B': '181819', '1F2937': '202021',
    '1F3A28': '0F2E1F', '221C17': '202021', '22C55E': '00B960', '22D3EE': '487BFF', '231A1D': '202021', '241503': '312720',
    '241E10': '312720', '241E19': '202021', '2563EB': '487BFF', '2A1F22': '202021', '2A231C': '282829', '2A241E': '282829',
    '2D2D44': '303031', '2D3548': '333334', '2E2410': '3E2C20', '322A22': '303031', '334155': '333334', '34D399': '3CD98A',
    '374151': '333334', '38302A': '333334', '3A1E1A': '411D1D', '3A322B': '333334', '3A3A5A': '4F4F50', '3B82F6': '4891FF',
    '3D2F33': '333334', '3D4555': '404041', '3DD6E0': '487BFF', '3E6E48': '007A3F', '3E827D': '2F62BF', '475569': '4F4F50',
    '4A3538': '4F4F50', '4A3728': '4F4F50', '4A3F36': '4F4F50', '4A4A6A': '4F4F50', '4ADE80': '3CD98A', '4E719C': '4A6FA8',
    '4E9C96': '3B78E0', '4E9E74': '00A355', '4E9E98': '3B78E0', '4F8B5C': '00934C', '4F9E97': '3B78E0', '5A3538': '4F4F50',
    '5C4449': '4F4F50', '5C4633': '4F4F50', '5C5348': '6B6B6D', '5E5449': '6B6B6D', '5E86B8': '5596E2', '5FB7B0': '4891FF',
    '60A5FA': '6FA8FF', '64748B': '858587', '67E8F9': '8FAEFF', '6B3E0A': '6B2E0A', '6E9C98': '6F8FBF', '6FBF7E': '00B960',
    '6FC7C0': '6FA8FF', '704214': '7A3510', '786D60': '858587', '7A5560': '858587', '7BD497': '3CD98A', '8B5CF6': '8333FC',
    '8FB488': '5CCB8F', '8FD3CD': '9CC2FF', '94A3B8': 'B4B4B6', '9BD9AB': '8AE6B5', '9BE0DA': 'A8C9FF', 'A78BFA': 'A879FF',
    'A79C8C': 'B4B4B6', 'A84E3F': 'C42F2F', 'A855F7': '8333FC', 'A96F22': 'B04500', 'ADA294': 'B4B4B6', 'C4B9AB': 'C8C8C9',
    'C6604F': 'E53E3E', 'C79A34': 'D65400', 'C9862E': 'D65400', 'CBD5E1': 'E0E0E0', 'CDEBD3': 'C2F2D8', 'D946EF': 'B93CF0',
    'D966FF': 'B93CF0', 'D98A3D': 'E8661A', 'D9B24E': 'FFB400', 'DC2626': 'E42525', 'E0705F': 'FA4D4D', 'E2E8F0': 'E8E8E8',
    'E3D8C8': 'E0E0E0', 'E6A24C': 'F37321', 'E6C766': 'FFB400', 'EAB308': 'FFB400', 'EC4899': 'FF5082', 'EDE6DB': 'F2F2F2',
    'EF4444': 'FA4D4D', 'F07A6C': 'FF7A7A', 'F0A73C': 'F37321', 'F0A79A': 'FFA8A8', 'F0C674': 'FFA86B', 'F1F5F9': 'F2F2F2',
    'F3E4BE': 'FFE0CC', 'F3ECE3': 'FFFFFF', 'F472B6': 'FF5082', 'F5988A': 'FF9494', 'F59E0B': 'FFB400', 'F5D4CD': 'FFD1D1',
    'FBBF24': 'FFB400', 'FCA5A5': 'FFA8A8', 'FCD9B6': 'FFD2B3', 'FF6B6B': 'FF7A7A', 'FFB13D': 'FF8A3D', 'FFC66E': 'FF9A5C',
    'FFD9A0': 'FFD2B3', 'FFE8C8': 'FFE6D6',
}
NEUTRAL_RAMP = ['000000', '101011', '181819', '202021', '282829', '303031', '333334', '404041',
                '4F4F50', '6B6B6D', '858587', 'B4B4B6', 'C8C8C9', 'E0E0E0', 'F2F2F2', 'FFFFFF']
FAMILY_HS = {'brand': (23/360, 0.89), 'warning': (42/360, 1.0), 'success': (151/360, 1.0),
             'info': (224/360, 1.0), 'purple': (264/360, 0.97), 'pink': (343/360, 1.0), 'error': (0, 0.95)}

def rgb(h): return tuple(int(h[i:i+2], 16) / 255 for i in (0, 2, 4))
def lum(h): r, g, b = rgb(h); return 0.2126*r + 0.7152*g + 0.0722*b
def hexs(r, g, b): return ''.join(f'{round(max(0, min(1, v))*255):02X}' for v in (r, g, b))
def norm(h): h = h.upper(); return ''.join(c*2 for c in h) if len(h) == 3 else h

def legacy_to_hv(h):
    """Map an arbitrary color onto the HV Dark palette (keeps lightness)."""
    if h in LEGACY: return LEGACY[h]
    r, g, b = rgb(h); hue, l, s = colorsys.rgb_to_hls(r, g, b); d = hue*360
    if s < 0.15 or l < 0.04 or l > 0.97 or (15 <= d <= 50 and (s < 0.25 or (s < 0.45 and l < 0.40) or (s < 0.55 and l > 0.80))):  # warm greys / creams = neutral
        return min(NEUTRAL_RAMP, key=lambda n: abs(lum(n) - lum(h)))
    fam = ('error' if d < 12 or d >= 345 else 'brand' if d < 40 else 'warning' if d < 62 else
           'success' if d < 175 else 'info' if d < 255 else 'purple' if d < 300 else 'pink')
    fh, fs = FAMILY_HS[fam]
    return hexs(*colorsys.hls_to_rgb(fh, l, min(fs, max(s, 0.55))))

# ── 1b. HV Dark value -> semantic token ──────────────────────────────────────
FG = {'brand': 'brand-fg', 'warning': 'warning-fg', 'success': 'success-fg', 'error': 'error-fg',
      'info': 'info-fg', 'purple': 'purple-fg'}
FAMILY_TOKENS = {
    'neutral': ['surface', 'widget-panel', 'widget', 'popup-panel', 'box', 'line', 'modal', 'line-strong', 'text-3', 'text-2', 'text'],
    'brand': ['brand-tint', 'brand-tint-strong', 'brand-hover', 'brand', 'brand-text'],
    'warning': ['warning-tint', 'warning-tint-strong', 'warning', 'warning-text'],
    'success': ['success-tint', 'success-tint-strong', 'success-hover', 'success-strong', 'success', 'success-text'],
    'error': ['error-tint', 'error-tint-strong', 'error-hover', 'error-strong', 'error', 'error-text'],
    'info': ['info-tint', 'info-tint-strong', 'info-strong', 'info', 'info-text'],
    'purple': ['purple-tint', 'purple', 'purple-text'], 'pink': ['pink'], 'violet': ['violet'],
}
EXACT = {'333334': 'line', '303031': 'box', '404041': 'modal', '6B6B6D': 'text-3', 'B4B4B6': 'text-2',
         'C8C8C9': 'text-2', 'E0E0E0': 'text', 'E8E8E8': 'text', 'F2F2F2': 'text', 'E8661A': 'brand',
         '487BFF': 'info', '4891FF': 'info', '3B78E0': 'info-strong', 'D65400': 'brand-hover'}
SOLID = {'brand', 'brand-hover', 'success-strong', 'success-hover', 'success', 'error-strong',
         'error-hover', 'error', 'info-strong', 'info', 'purple', 'violet', 'pink'}

def family(h):
    r, g, b = rgb(h); hue, l, s = colorsys.rgb_to_hls(r, g, b); d = hue*360
    if s < 0.15 or l < 0.05 or l > 0.97: return 'neutral'
    return ('error' if d < 12 or d >= 345 else 'brand' if d < 40 else 'warning' if d < 62 else
            'success' if d < 175 else 'info' if d < 255 else 'purple' if d < 285 else 'violet' if d < 300 else 'pink')

def snap(h):
    if h == '000000': return None
    h = legacy_to_hv(h)
    if h in EXACT: return EXACT[h]
    if h == 'FFFFFF': return 'text'
    return min(FAMILY_TOKENS[family(h)], key=lambda t: abs(lum(TOKENS[t][0]) - lum(h)))

def finalize(tok, text_ctx, raw, solid_line):
    if tok is None: return None
    if legacy_to_hv(raw) == 'FFFFFF' and solid_line: return 'WHITE'   # white label on a solid accent stays white
    if text_ctx and lum(raw) < 0.10: return 'INK'   # near-black text on a colored badge stays dark in both themes
    if text_ctx and tok in FG: return FG[tok]
    if text_ctx and tok == 'line-strong': return 'text-disabled'
    return tok

TW = re.compile(r'(?P<pre>[a-z:\-]*?(?:bg|text|border(?:-[trblxy])?|ring|ring-offset|from|to|via|fill|stroke|divide|outline|placeholder|shadow|accent|caret|decoration))-\[(?P<val>#[0-9A-Fa-f]{3,8}|rgba?\(\s*\d[^\]]*\))\](?P<alpha>/\d+)?')
HEX = re.compile(r'(?<!-\[)#([0-9A-Fa-f]{8}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{3})(?![0-9A-Za-z_-])')   # skips values already inside a Tailwind -[...] class, and ids like url(#cab-wall)
RGBA = re.compile(r'rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)')
PROP = re.compile(r'(\b[A-Za-z]+)\s*[:=]\s*\{?\s*[\'"`]?[^\'"`,;{}]*$')
stats = {}

def solid_on(line):
    if SOLID_CLS.search(line): return True      # already-tokenized solid accent background
    for m in HEX.finditer(line):
        if len(m.group(1)) == 8: continue
        pre = line[max(0, m.start()-30):m.start()]
        if line[m.end():m.end()+2] == ']/': continue          # translucent tint, not a solid fill
        if re.search(r'(bg-\[|background(Color)?\s*:\s*[\'"`]?)$', pre) and snap(norm(m.group(1))) in SOLID: return True
    for m in RGBA.finditer(line):
        pre = line[max(0, m.start()-30):m.start()]
        h = '%02X%02X%02X' % tuple(int(x) for x in m.groups()[:3])
        if not m.group(4) and re.search(r'background(Color)?\s*:\s*[\'"`]?$', pre) and snap(h) in SOLID: return True
    return False

def convert_line(line):
    if '#' not in line and 'rgb' not in line: return line
    solid = solid_on(line)
    def tw(m):
        pre, val, alpha = m.group('pre'), m.group('val'), m.group('alpha') or ''
        tctx = re.search(r'(?:^|-)(text|placeholder|caret|decoration)$', pre) is not None
        if val.startswith('#'):
            h = norm(val[1:7] if len(val) > 4 else val[1:]); a = int(val[7:9], 16)/255 if len(val) == 9 else None
        else:
            n = re.findall(r'[\d.]+', val); h = ''.join(f'{int(x):02X}' for x in n[:3]); a = float(n[3]) if len(n) > 3 else None
        tok = finalize(snap(h), tctx, h, solid); stats[tok or 'kept'] = stats.get(tok or 'kept', 0) + 1
        if tok == 'WHITE': return f'{pre}-[#FFFFFF]{alpha}'
        if tok == 'INK': return f'{pre}-[#101011]{alpha}'
        if not tok: return m.group(0)
        if a is not None and not alpha: alpha = f'/[{round(a, 2)}]'
        return f'{pre}-hv-{tok}{alpha}'
    line = TW.sub(tw, line)
    def ctx(i):
        m = PROP.search(line[:i]); p = m.group(1) if m else ''
        return p == 'color' or p.endswith('TextColor')
    def hx(m):
        v = m.group(1); h = norm(v[:6] if len(v) == 8 else v)
        tok = finalize(snap(h), ctx(m.start()), h, solid); stats[tok or 'kept'] = stats.get(tok or 'kept', 0) + 1
        if tok == 'WHITE': return '#FFFFFF' + (v[6:8] if len(v) == 8 else '')
        if tok == 'INK': return '#101011' + (v[6:8] if len(v) == 8 else '')
        if not tok: return m.group(0)
        if len(v) == 8: return f'rgb(var(--hv-{tok}) / {round(int(v[6:8], 16)/255, 2)})'
        return f'rgb(var(--hv-{tok}))'
    line = HEX.sub(hx, line)
    def rg(m):
        r, g, b, a = m.groups(); h = f'{int(r):02X}{int(g):02X}{int(b):02X}'
        if h == '000000': return m.group(0)
        if h == 'FFFFFF': tok = 'contrast'
        else: tok = finalize(snap(h), ctx(m.start()), h, False)
        if tok in ('WHITE', 'INK'): tok = None
        stats[tok or 'kept'] = stats.get(tok or 'kept', 0) + 1
        if not tok: return m.group(0)
        return f'rgb(var(--hv-{tok}) / {a})' if a else f'rgb(var(--hv-{tok}))'
    return RGBA.sub(lambda m: m.group(0) if 'var(--hv-' in m.group(0) else rg(m), line)

# ── 2-4. Line passes ─────────────────────────────────────────────────────────
SOLID_CLS = re.compile(r"bg-hv-(brand|brand-hover|success|success-strong|success-hover|error|error-strong|error-hover|info|info-strong|purple|violet|pink|data-[a-z]+)(?![\w-])(?!/)|bg-(red|rose|emerald|green|blue|sky|orange|cyan|teal|purple|violet|indigo|pink|amber|yellow)-(500|600|700)(?!/)|background(Color)?:\s*'rgb\(var\(--hv-(brand|success-strong|success|error-strong|error|info-strong|info|purple)\)\)'")
def pct(h): return f'{round(int(h, 16)/255*100)}%'

def convert_text(t):
    out = []
    for l in t.split('\n'):
        l = convert_line(l)
        if 'white' in l:
            l = re.sub(r'\b((?:[a-z]+:)*)bg-white/(\d+)', r'\1bg-hv-contrast/\2', l)
            if re.search(r'\btext-white\b', l) and not SOLID_CLS.search(' '.join(out[-2:] + [l])):
                l = re.sub(r'\btext-white\b', 'text-hv-text', l)
        if 'fixed inset-0' not in l:   # modal backdrops keep HV Dim black
            l = re.sub(r'(?<![\w-])((?:[a-z]+:)*)bg-black/(\d+)', r'\1bg-hv-surface/\2', l)
        if 'fixed inset-0' not in l and 'shadow' not in l.lower():
            l = re.sub(r"((?:background|backgroundColor)\s*:\s*')rgba\(\s*0\s*,\s*0\s*,\s*0\s*,\s*([\d.]+)\s*\)'", r"\1rgb(var(--hv-surface) / \2)'", l)
        l = re.sub(r"([A-Za-z_][\w.\[\]]*)\s*\+\s*'([0-9A-Fa-f]{2})'", lambda m: f"`color-mix(in srgb, ${{{m.group(1)}}} {pct(m.group(2))}, transparent)`", l)
        l = re.sub(r"\$\{([^{}]+)\}([0-9A-Fa-f]{2})(?=[\s,`)])", lambda m: f"color-mix(in srgb, ${{{m.group(1)}}} {pct(m.group(2))}, transparent)", l)
        out.append(l)
    return '\n'.join(out)

# ── 5. Categorical maps: one HV Data color per category ─────────────────────
DATA_MAPS = [
    # Workflow block types: light (pastel) tint, colored border and icon, theme text
    ('components/EmulationSection.tsx', r"(  %s:\s+\{[^\n]*?bgColor: ')[^']*(')", lambda t: f'bg-hv-{t}-tint text-hv-text border border-hv-{t}/40 [&_svg]:text-hv-{t}',
     {'reader': 'data-indigo', 'door': 'data-blue', 'io': 'data-yellow', 'wait': 'data-orange', 'schedule': 'data-green',
      'control': 'data-red', 'waitInput': 'data-sapphire', 'log': 'data-gray', 'supervision': 'data-coral', 'scenario': 'data-emerald'}),
    ('components/WiegandFormatVisualizer.tsx', r"('%s':\s*')rgb\(var\(--hv-[a-z0-9-]+\)\)(')", lambda t: f'rgb(var(--hv-{t}))',
     {'parity-even': 'data-green', 'parity-odd': 'data-yellow', 'parity-whole-odd': 'data-red', 'facility': 'data-blue',
      'card': 'data-purple', 'header': 'data-pink', 'oem': 'data-orange', 'issue-level': 'data-violet', 'xor-checksum': 'data-sapphire',
      'multi-row-ep1': 'data-emerald', 'multi-row-op': 'data-coral', 'multi-row-x': 'data-gray', 'multi-row-ep2': 'data-emerald'}),
    ('components/readers/formatLib.ts', r"(  '?%s'?: \{ color: ')rgb\(var\(--hv-[a-z0-9-]+\)\)(')", lambda t: f'rgb(var(--hv-{t}))',
     {'facility': 'data-blue', 'card': 'data-orange', 'issue': 'data-purple', 'tech': 'data-sapphire', 'agency': 'data-sapphire',
      'extra': 'data-gray', 'fixed': 'line-strong', 'pad': 'line', 'parity-even': 'data-green', 'parity-odd': 'data-red', 'parity': 'data-yellow'}),
    ('components/ControllerEmulatorSection.tsx', r"('%s':\s*\{\s*tint:\s*')rgb\(var\(--hv-[a-z0-9-]+\)\)(')", lambda t: f'rgb(var(--hv-{t}))',
     {'I16S': 'data-green', 'O8S': 'data-emerald', 'IO168S': 'data-blue', 'RI2MS': 'data-sapphire', 'RI4S': 'data-indigo'}),
]
def apply_data_maps(path, t):
    for rel, pat, val, mapping in DATA_MAPS:
        if str(path).replace('\\', '/').endswith(rel):
            for k, tok in mapping.items():
                t = re.sub(pat % re.escape(k), lambda m: m.group(1) + val(tok) + m.group(2), t, count=1)
    return t

# Drawings of physical things keep their real colors in both themes; after a conversion run,
# restore them with scripts/hv-artwork.py (needs the pre-HV commit it names in BASE).
ARTWORK = ('DoorAnimation.tsx', 'InteractiveReader.tsx', 'InteractiveWiegandReader.tsx', 'ElevatorSection.tsx', 'SwitchSection.tsx')

def main():
    src = pathlib.Path(sys.argv[1]); apply = '--apply' in sys.argv
    changed = []
    for p in sorted(src.rglob('*')):
        if p.suffix not in ('.ts', '.tsx') or not p.is_file() or 'theme' in p.parts: continue
        t = p.read_text(encoding='utf-8')
        nt = apply_data_maps(p, convert_text(t))
        if nt != t:
            changed.append(str(p))
            if apply: p.write_text(nt, encoding='utf-8')
    print(f"{'converted' if apply else 'would convert'} {len(changed)} files; tokens used: "
          + json.dumps(dict(sorted(stats.items(), key=lambda x: -x[1]))))
    for c in changed: print('  ' + c)
    if any(c.endswith(ARTWORK) for c in changed):
        print('  note: drawings were recolored; run scripts/hv-artwork.py --apply to restore their real colors')

if __name__ == '__main__':
    main()
