"""HV GUI Guidelines v3.435 semantic tokens used by Aether.
(dark, light) hex. Values come from the guideline's Tokens collection; translucent
tokens (borders, text tiers) are composited to solid values over their usual surface.
"""
TOKENS = {
    # Background / Surface
    'surface':        ('101011', 'EEEFF1'),
    'widget-panel':   ('181819', 'F9FAFB'),
    'widget':         ('202021', 'FFFFFF'),
    'popup-panel':    ('282829', 'F6F7F8'),
    'box':            ('303031', 'F6F7F8'),
    'modal':          ('404041', 'FFFFFF'),
    # Border / Normal
    'line':           ('333334', 'E0E1E3'),
    'line-strong':    ('4F4F50', 'C9CACC'),
    # Text / Normal
    'text':           ('FFFFFF', '000000'),
    'text-2':         ('C8C8C9', '3B3B3C'),
    'text-3':         ('858587', '767677'),
    'text-disabled':  ('4F4F50', 'C9C9CA'),
    # Contrast base for translucent overlays (white on dark, black on light)
    'contrast':       ('FFFFFF', '000000'),
    # Brand
    'brand':          ('F37321', 'F37321'),
    'brand-hover':    ('D65400', 'D65400'),
    'brand-text':     ('FF9A5C', 'C4520A'),
    'brand-tint':     ('3E2C20', 'FDEBE0'),
    'brand-tint-strong': ('6B2E0A', 'FAD3B8'),
    # Status — Warning
    'warning':        ('FFB400', 'FFA400'),
    'warning-text':   ('FFC633', '8F5A00'),
    'warning-tint':   ('33290F', 'FFF4D9'),
    'warning-tint-strong': ('5C4500', 'FFE2A3'),
    # Status — Success
    'success':        ('00B960', '008847'),
    'success-strong': ('00934C', '008847'),
    'success-hover':  ('007A3F', '006B38'),
    'success-text':   ('3CD98A', '006B38'),
    'success-tint':   ('0F2E1F', 'E0F5EA'),
    'success-tint-strong': ('175034', 'B8E8CE'),
    # Status — Error
    'error':          ('FA4D4D', 'E42525'),
    'error-strong':   ('E53E3E', 'D42020'),
    'error-hover':    ('C42F2F', 'B01C1C'),
    'error-text':     ('FF7A7A', 'C41C1C'),
    'error-tint':     ('311818', 'FDECEC'),
    'error-tint-strong': ('562222', 'F7C9C9'),
    # Status — Info / Data Blue
    'info':           ('4891FF', '4164F1'),
    'info-strong':    ('3B6BE6', '2F55D4'),
    'info-text':      ('6FA8FF', '2A47C4'),
    'info-tint':      ('182231', 'E8EEFE'),
    'info-tint-strong': ('1E3266', 'C7D5FC'),
    # Data colors
    'purple':         ('8333FC', '9A57E5'),
    'purple-text':    ('A879FF', '6B21D9'),
    'purple-tint':    ('241638', 'F1E8FD'),
    # Foreground use of status/brand colors (text, icons): same as base in Dark,
    # darkened in Light so text stays readable on white surfaces
    'brand-fg':       ('F37321', 'C4520A'),
    'warning-fg':     ('FFB400', '8F5A00'),
    'success-fg':     ('00B960', '006B38'),
    'error-fg':       ('FA4D4D', 'C41C1C'),
    'info-fg':        ('4891FF', '2A47C4'),
    'purple-fg':      ('8333FC', '6B21D9'),
    'pink':           ('FF5082', 'FF598E'),
    'violet':         ('B93CF0', 'B95AE5'),
    # HV Background/Data — categorical colors (charts, block types, frame types)
    'data-blue': ('4891FF', '5596E2'),
    'data-blue-tint': ('273449', 'E7F0FB'),
    'data-coral': ('FD6E55', 'FF816B'),
    'data-coral-tint': ('482E2A', 'FFEDEA'),
    'data-emerald': ('00B960', '56AB50'),
    'data-emerald-tint': ('1A3C2C', 'E7F3E6'),
    'data-gray': ('747779', '747E87'),
    'data-gray-tint': ('2F3031', 'ECEDEE'),
    'data-green': ('7DC519', '8EC63F'),
    'data-green-tint': ('313E20', 'EFF7E4'),
    'data-indigo': ('5A44EB', '647AED'),
    'data-indigo-tint': ('2A2645', 'E9ECFC'),
    'data-orange': ('FF6D10', 'F37321'),
    'data-orange-tint': ('482E1E', 'FDEBE0'),
    'data-pink': ('FF5082', 'FF598E'),
    'data-pink-tint': ('482932', 'FFE8EF'),
    'data-purple': ('8333FC', '9A57E5'),
    'data-purple-tint': ('322348', 'F1E7FB'),
    'data-red': ('FA4D4D', 'F65A5A'),
    'data-red-tint': ('472829', 'FEE8E8'),
    'data-sapphire': ('5071F2', '556ED7'),
    'data-sapphire-tint': ('292F47', 'E7EBF9'),
    'data-violet': ('B93CF0', 'B95AE5'),
    'data-violet-tint': ('3C2546', 'F5E8FB'),
    'data-yellow': ('FFB400', 'FFA400'),
    'data-yellow-tint': ('483B1B', 'FFF2DB'),
}

def ch(h):
    return f'{int(h[0:2],16)} {int(h[2:4],16)} {int(h[4:6],16)}'

def css():
    d = '\n'.join(f'  --hv-{k}: {ch(v[0])};' for k, v in TOKENS.items())
    l = '\n'.join(f'  --hv-{k}: {ch(v[1])};' for k, v in TOKENS.items())
    return f"""/*
 * HV GUI Guidelines v3.435 — semantic color tokens.
 * Each token holds RGB channels so Tailwind opacity modifiers work:
 *   className="bg-hv-widget border-hv-line text-hv-text-2"   bg-hv-brand/20
 *   style={{{{ color: 'rgb(var(--hv-text-3))' }}}}            rgb(var(--hv-error) / 0.3)
 * Theme is chosen by <html data-theme="dark|light">. Generated by scripts/hv-tokens.py — edit values there, then: python3 scripts/hv-tokens.py src/theme/hv-tokens.css
 */
:root, :root[data-theme="dark"] {{
  color-scheme: dark;
{d}
}}

:root[data-theme="light"] {{
  color-scheme: light;
{l}
}}
"""

if __name__ == '__main__':
    import sys
    open(sys.argv[1], 'w').write(css())
